import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { AppProvider } from "@/context/AppContext";
import { ToastProvider } from "@/context/ToastProvider";

const dmSans = localFont({
  variable: "--font-dm-sans",
  src: [
    {
      path: "./fonts/dm-sans/DMSans_18pt-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/dm-sans/DMSans_18pt-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});
const hankenGrotesk = localFont({
  variable: "--font-hanken-grotesk",
  src: [
    {
      path: "./fonts/Hanken-Grotesk/HankenGrotesk-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Hanken-Grotesk/HankenGrotesk-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "JetSend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} ${hankenGrotesk.className} antialiased`}
      >
        <AppProvider>
          <ToastProvider>{children}</ToastProvider>
        </AppProvider>
      </body>
    </html>
  );
}
